"""
API Utilities for Presentation Generation
Handles all external API integrations for generating visual assets.
"""

import os
import io
import requests
from PIL import Image
from typing import Optional, Dict, Any
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# API Keys
IDEOGRAM_API_KEY = os.getenv('IDEOGRAM_API_KEY')
PEXELS_API_KEY = os.getenv('PEXELS_API_KEY')
UNSPLASH_ACCESS_KEY = os.getenv('UNSPLASH_ACCESS_KEY')
ERASER_API_TOKEN = os.getenv('ERASER_API_TOKEN')


class APIUtils:
    """Utility class for API interactions"""

    @staticmethod
    def download_image(url: str, output_path: str) -> bool:
        """
        Download an image from a URL and save it locally.

        Args:
            url: The URL of the image
            output_path: Local path to save the image

        Returns:
            True if successful, False otherwise
        """
        try:
            response = requests.get(url, timeout=30)
            response.raise_for_status()

            with open(output_path, 'wb') as f:
                f.write(response.content)
            return True
        except Exception as e:
            print(f"Error downloading image from {url}: {e}")
            return False

    @staticmethod
    def generate_ideogram_image(prompt: str, output_path: str,
                                aspect_ratio: str = "ASPECT_16_9",
                                model: str = "V_2_TURBO") -> bool:
        """
        Generate an image using Ideogram API.

        Args:
            prompt: Text description of the image to generate
            output_path: Local path to save the generated image
            aspect_ratio: Image aspect ratio (ASPECT_16_9, ASPECT_1_1, ASPECT_9_16, etc.)
            model: Ideogram model to use (V_2_TURBO, V_2, V_1)

        Returns:
            True if successful, False otherwise
        """
        if not IDEOGRAM_API_KEY:
            print("Ideogram API key not found")
            return False

        url = "https://api.ideogram.ai/generate"
        headers = {
            "Api-Key": IDEOGRAM_API_KEY,
            "Content-Type": "application/json"
        }

        payload = {
            "image_request": {
                "prompt": prompt,
                "aspect_ratio": aspect_ratio,
                "model": model,
                "magic_prompt_option": "AUTO"
            }
        }

        try:
            response = requests.post(url, json=payload, headers=headers, timeout=60)
            response.raise_for_status()

            data = response.json()
            if data.get('data') and len(data['data']) > 0:
                image_url = data['data'][0]['url']
                return APIUtils.download_image(image_url, output_path)
            else:
                print("No image generated by Ideogram")
                return False

        except Exception as e:
            print(f"Error generating Ideogram image: {e}")
            return False

    @staticmethod
    def get_unsplash_image(query: str, output_path: str,
                          orientation: str = "landscape") -> bool:
        """
        Get a random image from Unsplash based on search query.

        Args:
            query: Search term
            output_path: Local path to save the image
            orientation: Image orientation (landscape, portrait, squarish)

        Returns:
            True if successful, False otherwise
        """
        if not UNSPLASH_ACCESS_KEY:
            print("Unsplash access key not found")
            return False

        url = "https://api.unsplash.com/photos/random"
        headers = {
            "Authorization": f"Client-ID {UNSPLASH_ACCESS_KEY}"
        }
        params = {
            "query": query,
            "orientation": orientation
        }

        try:
            response = requests.get(url, headers=headers, params=params, timeout=30)
            response.raise_for_status()

            data = response.json()
            image_url = data['urls']['regular']
            return APIUtils.download_image(image_url, output_path)

        except Exception as e:
            print(f"Error fetching Unsplash image: {e}")
            return False

    @staticmethod
    def get_pexels_image(query: str, output_path: str,
                        orientation: str = "landscape") -> bool:
        """
        Get an image from Pexels based on search query.

        Args:
            query: Search term
            output_path: Local path to save the image
            orientation: Image orientation (landscape, portrait, square)

        Returns:
            True if successful, False otherwise
        """
        if not PEXELS_API_KEY:
            print("Pexels API key not found")
            return False

        url = "https://api.pexels.com/v1/search"
        headers = {
            "Authorization": PEXELS_API_KEY
        }
        params = {
            "query": query,
            "orientation": orientation,
            "per_page": 1
        }

        try:
            response = requests.get(url, headers=headers, params=params, timeout=30)
            response.raise_for_status()

            data = response.json()
            if data.get('photos') and len(data['photos']) > 0:
                image_url = data['photos'][0]['src']['large']
                return APIUtils.download_image(image_url, output_path)
            else:
                print("No images found on Pexels")
                return False

        except Exception as e:
            print(f"Error fetching Pexels image: {e}")
            return False

    @staticmethod
    def generate_quickchart(chart_config: Dict[str, Any],
                           output_path: str,
                           width: int = 800,
                           height: int = 600) -> bool:
        """
        Generate a chart using QuickChart.io API.

        Args:
            chart_config: Chart.js configuration dictionary
            output_path: Local path to save the chart image
            width: Chart width in pixels
            height: Chart height in pixels

        Returns:
            True if successful, False otherwise
        """
        import json

        # Build QuickChart URL
        base_url = "https://quickchart.io/chart"
        params = {
            "c": json.dumps(chart_config),
            "width": width,
            "height": height
        }

        try:
            response = requests.get(base_url, params=params, timeout=30)
            response.raise_for_status()

            with open(output_path, 'wb') as f:
                f.write(response.content)
            return True

        except Exception as e:
            print(f"Error generating QuickChart: {e}")
            return False

    @staticmethod
    def get_dicebear_avatar(seed: str, output_path: str,
                           style: str = "avataaars", size: int = 200) -> bool:
        """
        Generate an avatar using DiceBear API.

        Args:
            seed: Seed for avatar generation (determines unique look)
            style: Avatar style (avataaars, bottts, pixel-art, etc.)
            output_path: Local path to save the avatar
            size: Avatar size in pixels

        Returns:
            True if successful, False otherwise
        """
        url = f"https://api.dicebear.com/7.x/{style}/png"
        params = {
            "seed": seed,
            "size": size
        }

        try:
            response = requests.get(url, params=params, timeout=30)
            response.raise_for_status()

            with open(output_path, 'wb') as f:
                f.write(response.content)
            return True

        except Exception as e:
            print(f"Error generating DiceBear avatar: {e}")
            return False

    @staticmethod
    def generate_mermaid_diagram(mermaid_code: str, output_path: str,
                                theme: str = "default") -> bool:
        """
        Generate a diagram from Mermaid code using mermaid.ink.

        Args:
            mermaid_code: Mermaid diagram code
            output_path: Local path to save the diagram
            theme: Diagram theme (default, dark, forest, neutral)

        Returns:
            True if successful, False otherwise
        """
        import base64

        # Encode mermaid code for URL
        encoded = base64.urlsafe_b64encode(mermaid_code.encode('utf-8')).decode('utf-8')
        url = f"https://mermaid.ink/img/{encoded}?theme={theme}"

        try:
            response = requests.get(url, timeout=30)
            response.raise_for_status()

            with open(output_path, 'wb') as f:
                f.write(response.content)
            return True

        except Exception as e:
            print(f"Error generating Mermaid diagram: {e}")
            return False


def test_apis():
    """Test all API integrations"""
    print("Testing API integrations...")

    # Create output directory
    os.makedirs("test_output", exist_ok=True)

    # Test QuickChart (no auth needed)
    print("\n1. Testing QuickChart...")
    chart_config = {
        "type": "bar",
        "data": {
            "labels": ["Q1", "Q2", "Q3", "Q4"],
            "datasets": [{
                "label": "Revenue",
                "data": [12, 19, 15, 25]
            }]
        }
    }
    if APIUtils.generate_quickchart(chart_config, "test_output/chart.png"):
        print("[OK] QuickChart working")

    # Test DiceBear (no auth needed)
    print("\n2. Testing DiceBear...")
    if APIUtils.get_dicebear_avatar("testuser", "test_output/avatar.png", style="avataaars"):
        print("[OK] DiceBear working")

    # Test Mermaid (no auth needed)
    print("\n3. Testing Mermaid...")
    mermaid_code = """
    graph LR
        A[Start] --> B[Process]
        B --> C[End]
    """
    if APIUtils.generate_mermaid_diagram(mermaid_code, "test_output/diagram.png"):
        print("[OK] Mermaid working")

    # Test Ideogram (requires API key)
    print("\n4. Testing Ideogram...")
    if IDEOGRAM_API_KEY:
        if APIUtils.generate_ideogram_image(
            "A professional business meeting in a modern office",
            "test_output/ideogram.png"
        ):
            print("[OK] Ideogram working")
    else:
        print("[WARN] Ideogram API key not found")

    # Test Unsplash (requires API key)
    print("\n5. Testing Unsplash...")
    if UNSPLASH_ACCESS_KEY:
        if APIUtils.get_unsplash_image("business", "test_output/unsplash.png"):
            print("[OK] Unsplash working")
    else:
        print("[WARN] Unsplash API key not found")

    # Test Pexels (requires API key)
    print("\n6. Testing Pexels...")
    if PEXELS_API_KEY:
        if APIUtils.get_pexels_image("technology", "test_output/pexels.png"):
            print("[OK] Pexels working")
    else:
        print("[WARN] Pexels API key not found")

    print("\n" + "="*50)
    print("API testing complete! Check test_output/ folder for generated assets.")


if __name__ == "__main__":
    test_apis()
